;; @check := [is_number; -> [n; ?== [n; 1]]]
;; @check := [is_string; -> [n; ?== [n; `[1]]]]
;; @check := [is_array; -> [n; ?== [n; .: []]]]
;; @check := [is_object; -> [n; ?== [n; :: []]]]
;; @check := [is_function; -> [n; ?== [n; -> [1]]]]
;; @check := [is_boolean; -> [n; || [== [n; 0]; == [n; 1]]]]
;; @check := [is_one_of; -> [key; strings; .: some [strings; -> [x; == [x; key]]]]]
;; @check := [is_empty_array; -> [arr; .: length [arr]]]
;; @check := [is_empty_object; -> [obj; :: size [obj]]]
